### ISSUE TITLE
[good first issue - beginner] Add Hamilton example using Vaex

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#457] opened 2023-10-12 23:12 UTC
**Is your feature request related to a problem? Please describe.**
[Vaex](https://github.com/vaexio/vaex) is a dataframe libary. We should have an example showing how you can use Hamilton with it.

**Describe the solution you'd like**
We should have an analogous hello world to the pandas example, but with Vaex. 

This will mean we'll need:
 - an example mirroring the Hamilton pandas hello world [beginner]
 - add a vaex extension mirroring the ones for [pandas and polars](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L20-L71) -- the materializers are not needed but the registry of types is. [beginner]
 - add a `h_vaex` to contain a result builder for vaex similar to the one for [polars](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/h_polars.py). [beginner]

**Describe alternatives you've considered**
N/A

**Additional context**
 - https://github.com/vaexio/vaex
 - https://vaex.io/docs/index.html

**Comment by tyapochkin** [comment] 2024-02-09 17:40
@skrawcz assign this issue to me, please

**Comment by tyapochkin** [comment] 2024-02-15 21:31
Just to note: Vaex still doesn't support python 3.11 and 3.12: https://github.com/vaexio/vaex/pull/2331. But it looks like it's under development right now.

**Comment by skrawcz** [comment] 2024-02-15 23:19
@tyapochkin cool -- that's fine.  

Does it look like Vaex is compatible with Hamilton? I just kind of assumed.

**Comment by tyapochkin** [comment] 2024-02-18 22:26
I've finally put together a working example with Hamilton and Vaex, so I can confirm that they are compatible. Well, at least in basic functionality and in-memory executions.
I'll finalize the code and tests and submit a PR shortly.

**Closed** 2024-02-24 06:28 UTC
Labels: good first issue, help wanted, hacktoberfest
