### ISSUE TITLE
Detect cycles at graph build time

### ISSUE THREAD

**Issue by adzcai** [DAGWorks-Inc/hamilton#1016] opened 2024-07-05 10:10 UTC
**Is your feature request related to a problem? Please describe.**
Hamilton doesn't prevent you from having cycles in the computation graph; this is not handled and raises a recursion depth error at runtime.

```python
from hamilton.driver import Driver
from hamilton.ad_hoc_utils import create_temporary_module

def foo(foo: int) -> int:
    return 42

mod = create_temporary_module(foo)
Driver({}, mod).execute(['foo'])  # RecursionError: maximum recursion depth exceeded
```

**Describe the solution you'd like**
Ideally an error would be thrown when constructing the driver. Not sure how easy this would be to detect.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by skrawcz** [comment] 2024-07-18 06:09
@adzcai I'm going to close this for now since this is intended behavior.

**Closed by skrawcz** 2024-07-18 06:09 UTC
Labels: wont fix
