### ISSUE TITLE
Parallel Execution: `KeyError: 'key df not found in cache'`

### ISSUE THREAD

**Issue by legout** [DAGWorks-Inc/hamilton#1029] opened 2024-07-17 07:38 UTC
The following example fails to run, when I add `df` to the final_vars with `KeyError: 'Key df not found in cache'`

![test_flow](https://github.com/user-attachments/assets/3549944a-d254-4f05-824c-44b964013ccd)

```python

from hamilton.htypes import Parallelizable, Collect
import random
import pandas as pd


# PARAMS = load_pipeline_cfg(
#    path=str(Path(__file__).parents[1] / "conf"), to_ht=True
# ).params.test_flow


def df_generator() -> Parallelizable[pd.DataFrame]:
    for i in range(10):
        yield pd.DataFrame(
            {"a": random.randint(0, 100), "b": [random.random() for i in range(100)]}
        )


def df(df_generator: pd.DataFrame) -> pd.DataFrame:
    return df_generator


def collect_df(df: Collect[pd.DataFrame]) -> list[pd.DataFrame]:
    return df


if __name__ == "__main__":
    import __main__ as test
    from hamilton import driver

    dr = (
        driver.Builder()
        .with_modules(test)
        .enable_dynamic_execution(allow_experimental_mode=True)
        .build()
    )

    final_vars = ["df", "collect_df"]
    r = dr.execute(final_vars=final_vars)

```

Complete Traceback

```python
Traceback (most recent call last):
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/pipelines/test_flow.py", line 42, in <module>
    r = dr.execute(final_vars=final_vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/.venv/lib/python3.12/site-packages/hamilton/driver.py", line 566, in execute
    raise e
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/.venv/lib/python3.12/site-packages/hamilton/driver.py", line 556, in execute
    outputs = self.raw_execute(_final_vars, overrides, display_graph, inputs=inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/.venv/lib/python3.12/site-packages/hamilton/driver.py", line 685, in raw_execute
    raise e
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/.venv/lib/python3.12/site-packages/hamilton/driver.py", line 674, in raw_execute
    results = self.graph_executor.execute(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/.venv/lib/python3.12/site-packages/hamilton/driver.py", line 234, in execute
    raw_result = results_cache.read(final_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z0043ddz/coding/projects/01__PrL/rte/.venv/lib/python3.12/site-packages/hamilton/execution/state.py", line 113, in read
    raise KeyError(f"Key {formatted_key} not found in cache")  # noqa E713
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Key df not found in cache'
```

Hamilton Version: 1.70.0

**Comment by skrawcz** [comment] 2024-07-17 15:08
@legout that's kind of expected behavior, because there would be potentially multiple `df` values. 

Do you have a situation where you want this functionality?

**Comment by skrawcz** [comment] 2024-07-18 18:50
Otherwise it's on our TODO to document / provide better handling as seen in #301

**Comment by legout** [comment] 2024-07-19 10:43
> @legout that's kind of expected behavior, because there would be potentially multiple `df` values.
> 
> Do you have a situation where you want this functionality?

No, I do not have a situation, where I really need this functionality. Just during developing/testing/debuging a dataflow, it would be nive to have the list of `df` available. I am aware, that this is possible by running the dataflow without the `collect_df`.

**Comment by skrawcz** [comment] 2024-08-10 22:12
Closing as this rolls up into #301

**Closed by skrawcz** 2024-08-10 22:12 UTC
Labels: duplicate
