### ISSUE TITLE
Parallel Execution: Collect node returns `list[list[pd.DataFrame]]` instead of `list[pd.DataFrame]`

### ISSUE THREAD

**Issue by legout** [DAGWorks-Inc/hamilton#1030] opened 2024-07-17 07:57 UTC
The following toy example returns a `list[list[pd.DataFrame]]` instead of `list[pd.DataFrame]`.

![test_flow](https://github.com/user-attachments/assets/22f6e012-b805-4dff-ac03-466bb31ba444)

```python
from hamilton.htypes import Parallelizable, Collect
import random
import pandas as pd


def df_generator() -> Parallelizable[pd.DataFrame]:
    for i in range(10):
        yield pd.DataFrame(
            {"a": random.randint(0, 100), "b": [random.random() for i in range(100)]}
        )



def collect_df(df_generator: Collect[pd.DataFrame]) -> list[pd.DataFrame]:
    return df_generator


if __name__ == "__main__":
    import __main__ as test
    from hamilton import driver

    dr = (
        driver.Builder()
        .with_modules(test)
        .enable_dynamic_execution(allow_experimental_mode=True)
        .build()
    )

    final_vars = ["collect_df"]
    r = dr.execute(final_vars=final_vars)

```

Hamilton Version: 1.70.0

**Comment by skrawcz** [comment] 2024-07-17 15:12
@legout thanks for catching this. This is an unusual situation, since using "Parallelizable" doesn't make sense here, as nothing is actually being Parallelized. That is, we _should_ expect a node in between them.

e.g. you'd instead do something like this:
```python
def df_generator() -> list[pd.DataFrame]:
    dfs = []
    for i in range(10):
        dfs.append(pd.DataFrame(
            {"a": random.randint(0, 100), "b": [random.random() for i in range(100)]}
        ))


def all_dfs(df_generator: list[pd.DataFrame]) -> pd.DataFrame:
    return pd.concat([df_generator])
```

Do you have more context here? Since I think we should probably error out in this situation -- thoughts?

**Comment by skrawcz** [comment] 2024-07-18 18:50
It's on our TODO to document / provide better handling as seen in https://github.com/DAGWorks-Inc/hamilton/issues/301

**Comment by legout** [comment] 2024-07-19 10:38
> @legout thanks for catching this. This is an unusual situation, since using "Parallelizable" doesn't make sense here, as nothing is actually being Parallelized. That is, we _should_ expect a node in between them.
> 
> Instead of Parallelizable, you'd instead do something like this:
> 
> ```python
> def df_generator() -> list[pd.DataFrame]:
>     dfs = []
>     for i in range(10):
>         dfs.append(pd.DataFrame(
>             {"a": random.randint(0, 100), "b": [random.random() for i in range(100)]}
>         ))
>     return dfs
> 
> 
> def all_dfs(df_generator: list[pd.DataFrame]) -> pd.DataFrame:
>     return pd.concat([df_generator])
> ```
> 
> Do you have more context here? Since I think we should probably error out in this situation -- thoughts?

@skrawcz 
Thanks for your fast response. For sure, this might be an unusual situation. But I wonder, if your alternative is really the same, when using a remote executor like MultiThreadingExecutor?

**Comment by skrawcz** [comment] 2024-07-19 16:54
> But I wonder, if your alternative is really the same, when using a remote executor like MultiThreadingExecutor?

So the way Parallelizable + Collect currently works is that only the code between them, is submitted to an executor. So in this example above, everything would be done serially - nothing would be submitted to be run in parallel.

To run that generation in parallel you'd instead want to do:

```python

from hamilton.htypes import Parallelizable, Collect
import random
import pandas as pd


def index() -> Parallelizable[int]:
    for i in range(10):
        yield i

def df_generator(index: int) -> pd.DataFrame:
     return pd.DataFrame(
            {"a": random.randint(0, 100), "b": [random.random() for i in range(100)]}
     )

def collect_df(df_generator: Collect[pd.DataFrame]) -> list[pd.DataFrame]:
    return df_generator


if __name__ == "__main__":
    import __main__ as test
    from hamilton import driver

    dr = (
        driver.Builder()
        .with_modules(test)
        .enable_dynamic_execution(allow_experimental_mode=True)
        .build()
    )

    final_vars = ["collect_df"]
    r = dr.execute(final_vars=final_vars)
```
Now - the usual caveats apply with doing anything in parallel in python. E.g. with multithreading CPU bound operations will likely mean things aren't done in parallel, but switching to multi-processing would work in parallel but you'd incur serialization/deserialization costs... So it only really makes sense to do if the time it takes to compute is long, which then makes parallelization worthwhile. Does that help?

**Comment by legout** [comment] 2024-07-20 08:47
Ok got it. Thanks for the detailed explanation!

**Comment by skrawcz** [comment] 2024-08-10 22:10
closing since I think we've explained the expected behavior.

**Closed by skrawcz** 2024-08-10 22:10 UTC
Labels: wont fix
